repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo-check
        language: system
        files: '\.rs$'
        entry: cargo check --verbose --all-targets --profile=test
        pass_filenames: false
      - id: rustfmt
        name: rustfmt
        language: system
        files: '\.rs$'
        entry: cargo fmt --all -- --check --verbose
      - id: clippy
        name: clippy
        language: system
        files: '\.rs$'
        entry: cargo clippy --all-targets --all-features -- -D warnings
        pass_filenames: false
      - id: rust-test-debug
        name: rust-test-debug
        language: system
        files: '\.rs$'
        entry: cargo test --verbose --locked
        pass_filenames: false
      - id: rust-test-release
        name: rust-test-debug
        language: system
        files: '\.rs$'
        entry: cargo test --verbose --locked --release
        pass_filenames: false

      - id: mix-test
        name: mix-test
        language: system
        files: '\.exs*$'
        entry: mix test
        pass_filenames: false
      - id: mix-fmt
        name: mix-fmt
        language: system
        files: '\.exs*$'
        entry: mix format --check-formatted
      - id: mix-compile
        name: mix-compile
        language: system
        files: '\.ex$'
        entry: mix compile --force --warnings-as-errors
        pass_filenames: false
      - id: mix-credo
        name: mix-credo
        language: system
        files: '\.exs*$'
        entry: mix credo
        pass_filenames: false
