[workspace]
members = [
    "sector",
    "sector-core",
    "sector-core/src/concurrency/native/sector-concurrency",
    "api",
]

[profile.release]
strip = true 
panic = "abort"
lto = true
opt-level = 'z'
codegen-units = 1
