[package]
name = "sector-api"
version = "0.1.0"
edition = "2021"
authors = ["Sector Developers"]
description = "Public interface for interacting with and extending SectorDB"
readme = "../README.md"

[dependencies]
sector_core = { path = "../sector-core/native/sector_core" }