[package]
name = "sector-concurrency"
version = "0.1.0"
edition = "2021"
authors = ["Sector Developers"]
readme = "../../../../../README.md"

[lib]
name = "sector_concurrency"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
